# Generated by Django 4.0 on 2021-12-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Covidstatus',
            fields=[
                ('person', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.person')),
                ('vaccine_name', models.CharField(blank=True, max_length=500, null=True)),
                ('vaccine_status', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'covidstatus',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vest', models.IntegerField(blank=True, null=True)),
                ('mask', models.IntegerField(blank=True, null=True)),
                ('keycard', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'equipment',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Parking',
            fields=[
                ('location_id', models.AutoField(primary_key=True, serialize=False)),
                ('car_number', models.IntegerField()),
                ('building', models.CharField(blank=True, max_length=500, null=True)),
                ('valid_until', models.DateField(blank=True, null=True)),
            ],
            options={
                'db_table': 'parking',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rewards',
            fields=[
                ('reward_id', models.AutoField(primary_key=True, serialize=False)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
                ('pointsofvolunteer', models.IntegerField(blank=True, db_column='pointsOfVolunteer', null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('referrals', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'rewards',
                'managed': False,
            },
        ),
    ]
