# Generated by Django 4.0 on 2021-12-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('room_number', models.AutoField(primary_key=True, serialize=False)),
                ('fname', models.CharField(blank=True, db_column='Fname', max_length=500, null=True)),
                ('lname', models.CharField(blank=True, db_column='Lname', max_length=500, null=True)),
                ('gender', models.CharField(blank=True, max_length=500, null=True)),
                ('bdate', models.DateField(blank=True, db_column='BDate', null=True)),
                ('pronouns', models.CharField(blank=True, max_length=500, null=True)),
                ('floor', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'patient',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sin', models.IntegerField(db_column='SIN')),
                ('password', models.CharField(max_length=500)),
                ('fname', models.CharField(db_column='FName', max_length=500)),
                ('minit', models.CharField(blank=True, db_column='Minit', max_length=5, null=True)),
                ('lname', models.CharField(db_column='LName', max_length=500)),
                ('bdate', models.DateField(db_column='BDate')),
                ('gender', models.CharField(db_column='Gender', max_length=500)),
                ('pronouns', models.CharField(blank=True, db_column='Pronouns', max_length=45, null=True)),
                ('backgroundcheck', models.IntegerField(db_column='BackgroundCheck')),
                ('role', models.CharField(db_column='Role', max_length=500)),
            ],
            options={
                'db_table': 'person',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Coordinator',
            fields=[
                ('c', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.person')),
                ('salary', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'coordinator',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Externalvolunteer',
            fields=[
                ('ev', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.person')),
                ('specialty', models.CharField(blank=True, max_length=500, null=True)),
                ('affiliated_company', models.CharField(blank=True, max_length=500, null=True)),
                ('pet_visit_flag', models.IntegerField(blank=True, null=True)),
                ('spirit_flag', models.IntegerField(blank=True, null=True)),
                ('pet_name', models.CharField(blank=True, max_length=500, null=True)),
                ('pet_type', models.CharField(blank=True, max_length=500, null=True)),
                ('faith', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'externalvolunteer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Potentialvolunteer',
            fields=[
                ('pv', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.person')),
                ('backgroundcheckstatus', models.IntegerField(blank=True, db_column='backgroundCheckStatus', null=True)),
                ('referral', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'potentialvolunteer',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('v', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.person')),
                ('start_date', models.DateField(blank=True, null=True)),
                ('training_year', models.IntegerField(blank=True, null=True)),
                ('training_level', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'volunteer',
                'managed': False,
            },
        ),
    ]
