# Generated by Django 4.0 on 2021-12-17 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assign',
            fields=[
                ('a', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'assign',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Seminar',
            fields=[
                ('seminar_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'seminar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Shift',
            fields=[
                ('shift_id', models.IntegerField(primary_key=True, serialize=False)),
                ('date', models.DateField(blank=True, null=True)),
                ('time', models.TimeField(blank=True, null=True)),
                ('place', models.CharField(blank=True, max_length=500, null=True)),
                ('volunteers_assigned', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'shift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Attends',
            fields=[
                ('sem', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='Signup.seminar')),
            ],
            options={
                'db_table': 'attends',
                'managed': False,
            },
        ),
    ]
