# Generated by Django 4.0 on 2021-12-18 00:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0001_initial'),
        ('Signup', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reflections',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('comments', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'db_table': 'reflections',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Visits',
            fields=[
                ('v_sin', models.OneToOneField(db_column='v_sin', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to='User.person')),
            ],
            options={
                'db_table': 'visits',
                'managed': False,
            },
        ),
    ]
